[package]
name = "arborium-mdbook"
version = "<%= version %>"
edition = "2021"

[dependencies]
anyhow = "1"
arborium = { version = "<%= version %>", path = "../arborium" }
mdbook = "0.4"
pulldown-cmark = { version = "0.13", default-features = false, features = ["simd"] }
pulldown-cmark-to-cmark = "21.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
html-escape = "0.2"
