name = "elisp"
tag = "code"
icon = "simple-icons:gnuemacs"
aliases = ["emacs-lisp", "el"]
repo = ""
commit = ""
license = ""
inventor = "Richard Stallman"
year = 1985
description = ""
link = "https://en.wikipedia.org/wiki/Emacs_Lisp"
trivia = ""

