id = "elisp"
tier = 4
name = "Emacs Lisp"
tag = "code"
icon = "simple-icons:gnuemacs"
aliases = ["emacs-lisp", "el"]
repo = ""
commit = ""
license = ""
inventor = "Richard Stallman"
year = 1985
description = "A Lisp dialect used to extend and customize the GNU Emacs text editor."
link = "https://en.wikipedia.org/wiki/Emacs_Lisp"
trivia = "Emacs Lisp has been called 'the most widely used Lisp dialect' due to Emacs's popularityâ€”millions of lines of Elisp packages exist."


[[samples]]
path = "samples/simple.el"
description = "Emacs simple.el with defuns, defvars, and interactive commands."
link = "https://github.com/emacs-mirror/emacs/blob/master/lisp/simple.el"
license = "GPL-3.0"
