name = "uiua"
tag = "code"
icon = "mdi:alpha-u-box-outline"
aliases = ["ua"]
repo = ""
commit = ""
license = ""
inventor = "Daniel Diaz"
year = 2023
description = ""
link = "https://www.uiua.org"
trivia = ""

