name = "matlab"
tag = "code"
icon = "devicon-plain:matlab"
aliases = ["m"]
repo = ""
commit = ""
license = ""
inventor = "Cleve Moler"
year = 1984
description = ""
link = "https://en.wikipedia.org/wiki/MATLAB"
trivia = ""

