[package]
name = "arborium-test-harness"
version = "<%= version %>"
edition = "2024"
rust-version = "1.85"
description = "Test harness for arborium grammar crates"
authors = ["Amos Wenger <amos@bearcove.eu>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/bearcove/arborium"
homepage = "https://github.com/bearcove/arborium"
documentation = "https://docs.rs/arborium-test-harness"
keywords = ["syntax-highlighting", "tree-sitter", "testing"]
categories = ["development-tools::testing"]

[dependencies]
arborium-highlight = { version = "<%= version %>", path = "../arborium-highlight", features = ["tree-sitter"] }
arborium-theme = { version = "<%= version %>", path = "../arborium-theme" }
arborium-tree-sitter = { version = "<%= version %>", path = "../arborium-tree-sitter" }
tree-sitter-language = { version = "0.1", path = "../arborium-tree-sitter/language" }
