name = "thrift"
tag = "data"
icon = "mdi:swap-horizontal"
repo = "https://github.com/tree-sitter-grammars/tree-sitter-thrift"
commit = "68fd0d80943a828d9e6f49c58a74be1e9ca142cf"
license = "MIT"
inventor = "Facebook"
year = 2007
description = "Interface Definition Language and RPC framework; official Apache docs at [thrift.apache.org](https://thrift.apache.org/docs)."
link = "https://en.wikipedia.org/wiki/Apache_Thrift"
trivia = "Developed at Facebook starting 2006, open-sourced 2007; entered Apache Incubator in 2008 and became a TLP in 2010â€”see the [Apache Thrift history](https://thrift.apache.org/)."

[[samples]]
path = "samples/tutorial.thrift"
description = "Official Apache Thrift tutorial showing services, structs, enums, and exceptions."
link = "https://github.com/apache/thrift/blob/master/tutorial/tutorial.thrift"
license = "Apache-2.0"
