name = "rescript"
tag = "code"
icon = "simple-icons:rescript"
aliases = ["res"]
repo = "https://github.com/rescript-lang/tree-sitter-rescript"
commit = "d2df8a285fff95de56a91d2f8152aeceb66f40ef"
license = "MIT"
inventor = "Hongbo Zhang and the ReScript team"
year = 2020
description = "Functional language that compiles to JavaScript, evolved from BuckleScript/Reason; docs at [rescript-lang.org](https://rescript-lang.org/docs/latest)."
link = "https://rescript-lang.org/"
trivia = "Rebranded from BuckleScript/Reason in 2020 to focus on a JS-centric pipeline; see the [ReScript announcement](https://rescript-lang.org/blog/announcement) and docs for the syntax and compiler."

[[samples]]
path = "samples/Demo.res"
description = "ReScript project template demo component with JSX-like syntax and bindings."
link = "https://github.com/rescript-lang/rescript-project-template/blob/master/src/Demo.res"
license = "MIT"
