name = "ssh-config"
tag = "config"
icon = "mdi:key-chain"
repo = ""
commit = ""
license = ""
inventor = "Tatu Yl√∂nen"
year = 1995
description = ""
link = "https://man.openbsd.org/ssh_config"
trivia = ""

