name = "diff"
tag = "data"
icon = "mdi:file-compare"
aliases = ["patch"]
repo = "https://github.com/the-mikedavis/tree-sitter-diff"
commit = "2520c3f934b3179bb540d23e0ef45f75304b5fed"
license = "MIT"
inventor = "Wayne Davison"
year = 1990
description = "Unified diff format for representing file differences; GNU diffutils manual documents the format ([GNU diffutils](https://www.gnu.org/software/diffutils/manual/))."
link = "https://en.wikipedia.org/wiki/Diff"
trivia = "Wayne Davison proposed the unified format in Aug 1990 on comp.sources.misc; GNU diff added support in version 1.15 (Jan 1991) per the [diffutils ChangeLog](https://git.savannah.gnu.org/gitweb/?p=diffutils.git;a=blob;f=NEWS;hb=refs/tags/v1.15)."

[[samples]]
path = "sample.diff"
description = ""
link = ""
license = ""
