name = "graphql"
tag = "query"
icon = "devicon-plain:graphql"
aliases = ["gql"]
repo = ""
commit = ""
license = ""
inventor = "Lee Byron, Nick Schrock"
year = 2012
description = ""
link = "https://en.wikipedia.org/wiki/GraphQL"
trivia = ""

