name = "d"
tag = "code"
icon = "mdi:alpha-d-box-outline"
aliases = ["dlang"]
repo = ""
commit = ""
license = ""
inventor = "Walter Bright"
year = 2001
description = ""
link = "https://en.wikipedia.org/wiki/D_(programming_language)"
trivia = ""

