name = "vhdl"
tag = "code"
icon = "mdi:chip"
aliases = ["vhd"]
repo = "https://github.com/alemuller/tree-sitter-vhdl"
commit = "a3b2d84990527c7f8f4ae219c332c00c33d2d8e5"
license = "MIT"
inventor = "U.S. Department of Defense"
year = 1983
description = "VHSIC Hardware Description Language; standardized as [IEEE 1076](https://standards.ieee.org/ieee/1076/7424/)."
link = "https://en.wikipedia.org/wiki/VHDL"
trivia = "Developed under the VHSIC program and standardized in 1987 as IEEE 1076; later revisions added numeric_std and child standards."

[[samples]]
path = "samples/issue1220.vhdl"
description = "GHDL test case exercising VHDL entities, architectures, signals, and synthesis edge cases."
link = "https://github.com/ghdl/ghdl/blob/master/testsuite/synth/issue1220.vhdl"
license = "GPL-2.0-or-later"
