name = "sparql"
tag = "query"
icon = "mdi:graph-outline"
aliases = ["rq"]
repo = ""
commit = ""
license = ""
inventor = "W3C RDF Data Access Working Group"
year = 2008
description = ""
link = "https://en.wikipedia.org/wiki/SPARQL"
trivia = ""

