id = "sparql"
tier = 5
name = "SPARQL"
tag = "query"
icon = "mdi:graph-outline"
aliases = ["rq"]
repo = ""
commit = ""
license = ""
inventor = "W3C RDF Data Access Working Group"
year = 2008
description = "A query language for retrieving and manipulating data stored in RDF (Resource Description Framework) format."
link = "https://en.wikipedia.org/wiki/SPARQL"
trivia = "SPARQL is a recursive acronym: 'SPARQL Protocol and RDF Query Language'â€”it powers knowledge graphs like Wikidata and DBpedia."


[[samples]]
path = "samples/query.sparql"
description = "SPARQL queries with SELECT, CONSTRUCT, FILTER, and aggregations."
license = "CC0-1.0"
