name = "asciidoc"
tag = "markup"
icon = "mdi:text-box"
aliases = ["adoc"]
repo = ""
commit = ""
license = ""
inventor = "Stuart Rackham"
year = 2002
description = ""
link = "https://en.wikipedia.org/wiki/AsciiDoc"
trivia = ""

