name = "perl"
tag = "code"
icon = "devicon-plain:perl"
aliases = ["pl", "pm"]
repo = "https://github.com/tree-sitter-perl/tree-sitter-perl"
commit = "ad74e6db234c35d537de9358799a8e0cc4f5dee0"
license = "MIT"
inventor = "Larry Wall"
year = 1987
description = "General-purpose scripting language renowned for text processing; core docs at [perldoc.perl.org](https://perldoc.perl.org/)."
link = "https://en.wikipedia.org/wiki/Perl"
trivia = "Wall released Perl 1.0 on 18 Dec 1987; the motto 'There's more than one way to do it' is from the official [perlstyle](https://perldoc.perl.org/perlstyle) and [perlintro](https://perldoc.perl.org/perlintro) documentation."

[[samples]]
path = "samples/hello.pl"
description = "Mojolicious hello world showing routes, rendering, and startup."
link = "https://github.com/mojolicious/mojo/blob/master/examples/hello.pl"
license = "Artistic-2.0"
