name = "xml"
tag = "markup"
icon = "devicon-plain:xml"
aliases = ["xsl", "xslt", "svg"]
repo = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
commit = "863dbc381f44f6c136a399e684383b977bb2beaa"
license = "MIT"
subdir = "xml"  # Multi-grammar repo: use xml/ subdirectory
inventor = "W3C XML Working Group"
year = 1998
description = "Extensible Markup Language defined by the [W3C XML 1.0 Recommendation](https://www.w3.org/TR/xml/)."
link = "https://en.wikipedia.org/wiki/XML"
trivia = "Work began in 1996; XML 1.0 became a W3C Recommendation on Feb 10, 1998, led by Bray, Paoli, and Sperberg-McQueen."

[[samples]]
path = "samples/pom.xml"
description = "Spring Petclinic Maven POM with dependencies, plugins, profiles, and properties."
link = "https://github.com/spring-projects/spring-petclinic/blob/main/pom.xml"
license = "Apache-2.0"
