name = "elixir"
repo = "https://github.com/elixir-lang/tree-sitter-elixir"
commit = "d24cecee673c4c770f797bac6f87ae4b6d7ddec5"
license = "Apache-2.0"
inventor = "Jos√© Valim"
year = 2011
description = "Functional, concurrent language on the BEAM VM; official site: [elixir-lang.org](https://elixir-lang.org/)."
wikipedia = "https://en.wikipedia.org/wiki/Elixir_(programming_language)"
trivia = "Valim announced Elixir in 2011 to blend Ruby-like ergonomics with Erlang's fault-tolerance; see the [Elixir getting started guide](https://elixir-lang.org/getting-started/introduction.html) and the original [announcement post](https://elixir-lang.org/blog/2011/01/09/introducing-elixir/)."

[[samples]]
path = "sample.ex"
description = ""
link = ""
license = ""
