name = "scala"
tag = "code"
icon = "devicon-plain:scala"
repo = "https://github.com/tree-sitter/tree-sitter-scala"
commit = "97aead18d97708190a51d4f551ea9b05b60641c9"
license = "MIT"
inventor = "Martin Odersky"
year = 2004
description = "Multi-paradigm JVM language blending OO and FP; official docs at [scala-lang.org](https://docs.scala-lang.org/)."
link = "https://en.wikipedia.org/wiki/Scala_(programming_language)"
trivia = "The name abbreviates 'scalable language'; Odersky announced Scala in 2004 after work on Java generics and the Pizza language. The [Scala 3 reference](https://docs.scala-lang.org/scala3/reference/) documents current syntax and features."

[[samples]]
path = "samples/SparkPi.scala"
description = "Apache Spark example computing Pi using RDDs, showing objects, methods, and functional style."
link = "https://github.com/apache/spark/blob/master/examples/src/main/scala/org/apache/spark/examples/SparkPi.scala"
license = "Apache-2.0"

# amos-picked sample
[[samples]]
path = "samples/ResultResolver.scala"
description = "Sangria GraphQL result resolver with Futures, cats-style Eithers, and async execution."
link = "https://github.com/sangria-graphql/sangria/blob/main/modules/core/src/main/scala/sangria/execution/ResultResolver.scala"
license = "Apache-2.0"
