name = "julia"
tag = "code"
icon = "devicon-plain:julia"
aliases = ["jl"]
repo = ""
commit = ""
license = ""
inventor = "Jeff Bezanson, Stefan Karpinski, Viral B. Shah, Alan Edelman"
year = 2012
description = ""
link = "https://en.wikipedia.org/wiki/Julia_(programming_language)"
trivia = ""

