name = "cmake"
tag = "build"
icon = "devicon-plain:cmake"
repo = ""
commit = ""
license = ""
inventor = "Bill Hoffman"
year = 2000
description = ""
link = "https://en.wikipedia.org/wiki/CMake"
trivia = ""

