name = "textproto"
tag = "data"
icon = "mdi:message-outline"
aliases = ["pbtxt", "textpb"]
repo = ""
commit = ""
license = ""
inventor = "Google"
year = 2001
description = ""
link = "https://github.com/protocolbuffers/protobuf"
trivia = ""

