name = "commonlisp"
tag = "code"
icon = "mdi:lambda"
aliases = ["lisp", "cl"]
repo = ""
commit = ""
license = ""
inventor = "ANSI X3J13 committee"
year = 1984
description = ""
link = "https://en.wikipedia.org/wiki/Common_Lisp"
trivia = ""

