name = "typst"
tag = "markup"
icon = "simple-icons:typst"
aliases = ["typ"]
repo = ""
commit = ""
license = ""
inventor = "Typst Labs"
year = 2022
description = ""
link = "https://typst.app"
trivia = ""

