name = "fish"
tag = "shell"
icon = "mdi:fish"
repo = ""
commit = ""
license = ""
inventor = "Axel Liljencrantz"
year = 2005
description = ""
link = "https://en.wikipedia.org/wiki/Friendly_interactive_shell"
trivia = ""

